#include <iostream>
#include <istream>
#include <fstream>
#include <vector>
#include <cstdint>
#include <cstring>

#include <SDL3/SDL.h>
#include <SDL3/SDL_vulkan.h>
#include <SDL3/SDL_main.h>
#include "vkobjects.h"

#include "tga.h"
#include "math.h"
#include "camera.h"

// Global Settings
int windowWidth = 1280;
int windowHeight = 720;
size_t computedQuadCount = 100;

struct SDLWindow {
    SDL_Window *window;
    SDLWindow(const char * title, int w, int h) {
        if (false == SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
            throw std::runtime_error("Failed to initialize SDL");
        }
        window = SDL_CreateWindow(title, w, h, SDL_WINDOW_VULKAN);
        if (window == nullptr) {
            throw std::runtime_error("Failed to create SDL window");
        }
    }
    ~SDLWindow() {
        SDL_DestroyWindow(window);
        SDL_Quit();
    }
    operator SDL_Window*() {
        return window;
    }
};

struct Timer {
    size_t lastTicks;
    Timer():lastTicks(SDL_GetTicks()){ }
    size_t elapsed() {
        size_t now = SDL_GetTicks();
        size_t elapsed = now - lastTicks;
        lastTicks = now;
        return elapsed;
    }
};

Image createImageFromTGAFile(Commands & commands, const char * filename) {
    std::ifstream file(filename, std::ios::binary);
    std::vector<uint8_t> fileBytes = std::vector<uint8_t>(
        std::istreambuf_iterator<char>(file),
        std::istreambuf_iterator<char>());

    file.close();
    unsigned width, height;
    int bpp;
    void* bytes = read_tga(fileBytes, width, height, bpp);
    if (bytes == nullptr) {
        throw std::runtime_error("failed to read file as TGA");
    }

    unsigned byteCount = width*height*(bpp/8);
    VkFormat format = (bpp == 32) ? VK_FORMAT_B8G8R8A8_SRGB : VK_FORMAT_B8G8R8_SRGB;

    Buffer stagingBuffer(BufferBuilder(byteCount).transferSource().hostVisible());
    stagingBuffer.upload(bytes, byteCount);
    free(bytes);

    Image image(ImageBuilder().fromStagingBuffer(stagingBuffer, width, height, format), commands);
    return image;
}

// Push constants — viewProjection and resource IDs all in one struct
struct PushConstants {
    float viewProjection[16]; // mat4
    float zScale;
    uint32_t vertexBufferRID;
    uint32_t textureRID;
};

int main(int argc, char *argv[]) {
    (void)argc;
    (void)argv;
    SDLWindow window("VulkanApp", windowWidth, windowHeight);

    VulkanContext context(window, VulkanContextOptions().validation().meshShaders());

    // shaders
    ShaderModule fragShaderModule(ShaderBuilder().fragment().fromFile("src/shaders/tri.frag.spv"));
    ShaderModule compShaderModule(ShaderBuilder().compute().fromFile("src/shaders/vertices.comp.spv"));
    ShaderModule meshShaderModule(ShaderBuilder().mesh().fromFile("src/shaders/quad.mesh.spv"));

    // one-shot setup commands
    auto setupCmd = Commands::oneShot();
    Image textureImage = createImageFromTGAFile(setupCmd, "vulkan.tga");
    ImageBuilder depthImageBuilder = ImageBuilder().depth();
    std::vector<Image> depthImages;
    for (size_t i = 0; i < context.swapchainImageCount; ++i) {
        depthImages.emplace_back(depthImageBuilder, setupCmd);
    }
    setupCmd.submitAndWait();

    // resize callback — recreate depth images on swapchain rebuild
    context.onSwapchainResize([&](Commands & cmd, VkExtent2D extent) {
        (void)extent;
        depthImages.clear();
        for (size_t i = 0; i < context.swapchainImageCount; ++i) {
            depthImages.emplace_back(ImageBuilder().depth(), cmd);
        }
    });

    // buffer for vertex data generated by compute shader
    Buffer shaderStorageVertexBuffer(BufferBuilder(sizeof(float) * 5 * 6 * computedQuadCount).storage());

    // pipelines use the context's bindless pipeline layout
    Pipeline graphicsPipeline = GraphicsPipelineBuilder()
        .meshShader(meshShaderModule)
        .fragmentShader(fragShaderModule)
        .build();

    Pipeline computePipeline = createComputePipeline(compShaderModule);

    Camera camera;
    camera.perspective(0.5f*M_PI, windowWidth, windowHeight, 0.1f, 100.0f)
        .moveTo(1.0f, 0.0f, -0.5f)
        .lookAt(0.0f, 0.0f, 0.0f)
        .moveTo(0.0f, 0.0f, 0.0f)
        .setDistance(1.0f);

    PushConstants push = {};
    push.zScale = 0.2f;

    Timer timer;
    bool done = false;
    while (!done) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_QUIT) {
                done = true;
            }
        }

        Frame frame;

        // Rotate camera and update push constants
        float seconds = (float)timer.elapsed() / 1000.0f;
        camera.rotate(0.0f, 1.0f, 0.0f, M_PI * seconds / 2.0);
        mat16f vp = camera.getViewProjection();
        memcpy(push.viewProjection, &vp, sizeof(mat16f));
        push.vertexBufferRID = shaderStorageVertexBuffer.rid();
        push.textureRID = textureImage.rid();

        auto cmd = frame.beginCommands();

        // Compute pass: generate vertex data
        cmd.bindCompute(computePipeline);
        cmd.pushConstants(&push, sizeof(push));
        cmd.dispatch(1, 1, 1);

        // Barrier: compute writes → mesh shader reads
        cmd.bufferBarrier(shaderStorageVertexBuffer, Stage::Compute, Stage::MeshShader);

        // Render pass
        cmd.beginRendering(depthImages[frame.swapchainImageIndex()].imageView);
        cmd.bindGraphics(graphicsPipeline);
        cmd.pushConstants(&push, sizeof(push));
        cmd.drawMeshTasks(computedQuadCount, 1, 1);
        cmd.endRendering();

        frame.submit(cmd);
    }

    if (VK_SUCCESS != vkQueueWaitIdle(context.graphicsQueue)) {
        throw std::runtime_error("failed to wait for the graphics queue to be idle");
    }
}
